rootProject.name = "JBotWithUsV2"

include("api", "core", "cli", "example-script", "test-support")

// Modules generated by ./gradlew createScript register themselves via
// additionalScripts.txt at the project root — one Gradle path per line
// (e.g. ":my-script"). The file is opt-in: nothing breaks if it doesn't
// exist or is empty. Lines starting with '#' are treated as comments;
// blank lines are skipped.
val additionalScriptsFile = rootDir.resolve("additionalScripts.txt")
if (additionalScriptsFile.exists()) {
    additionalScriptsFile.readLines()
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("#") }
            .forEach { include(it) }
}
