package com.botwithus.bot.api.model;

import java.util.HashMap;
import java.util.Map;

/**
 * World map icon names extracted from the game cache. Each constant holds the
 * exact display name used by the corresponding {@link WorldMapElement}, suitable
 * for passing to {@link com.botwithus.bot.api.entities.WorldMapElements.Query#named Query.named()}.
 *
 * @see WorldMapElement
 * @see com.botwithus.bot.api.entities.WorldMapElements
 */
public enum WorldMapIcon {

    ABANDONED_MINE("Abandoned Mine"),
    ABERRANT_SPECTRES("Aberrant spectres"),
    ABYSSAL_DEMONS("Abyssal demons"),
    ACCESS_TO_FALADOR("Access to Falador"),
    ACROPOLIS("Acropolis"),
    ADMIRAL_WADUD("Admiral Wadud"),
    AGILITY_ARENA("Agility Arena"),
    AGILITY_PYRAMID("Agility Pyramid"),
    AGILITY_TRAINING_AREA("Agility Training Area"),
    AGILITY_COURSE("Agility course"),
    AGILITY_COURSE_SPIKES("Agility course spikes"),
    AIRUT("Airut"),
    AL_KHARID("Al Kharid"),
    ALTAR("Altar"),
    AMINISHI("Aminishi"),
    AMLODD("Amlodd"),
    AMPHITHEATRE("Amphitheatre"),
    ANACHRONIA("Anachronia"),
    ANACHRONIA_DINOSAUR_FARM("Anachronia Dinosaur Farm"),
    ANCIENT_PRISON("Ancient Prison"),
    ANCIENT_CAVERN("Ancient cavern"),
    ANGER("Anger"),
    ANIMATED_AXES("Animated axes"),
    APE_ATOLL("Ape Atoll"),
    AQUANITES("Aquanites"),
    ARANDAR("Arandar"),
    ARCHAEOLOGY_CAMPUS("Archaeology Campus"),
    ARCHAEOLOGY_GUILD("Archaeology Guild"),
    ARDOUGNE_MONASTERY("Ardougne Monastery"),
    ARDOUGNE_SEWERS("Ardougne Sewers"),
    ARDOUGNE_ZOO("Ardougne Zoo"),
    ARMADYLS_EYRIE("Armadyl's Eyrie"),
    ARMADYLS_TOWER("Armadyl's Tower"),
    ARTISANS_WORKSHOP("Artisans' Workshop"),
    ASHDALE("Ashdale"),
    ASTRAM_FARM("Astram Farm"),
    BAG_OF_SUPPLIES("Bag of supplies"),
    BANDIT_CAMP("Bandit Camp"),
    BANDOSS_STRONGHOLD("Bandos's Stronghold"),
    BANDOSS_TOWER("Bandos's Tower"),
    BANDOSS_SANCTUM("Bandos's sanctum"),
    BANK("Bank"),
    BANK_VAULT("Bank vault"),
    BANSHEES("Banshees"),
    BARBARIAN_ASSAULT("Barbarian Assault"),
    BARBARIAN_OUTPOST("Barbarian Outpost"),
    BARBARIAN_VILLAGE("Barbarian Village"),
    BARRACKS("Barracks"),
    BARROWS("Barrows"),
    BASILISKS("Basilisks"),
    BATAL("Batal"),
    BATS("Bats"),
    BATTLEFIELD("Battlefield"),
    BAXTORIAN_FALLS("Baxtorian Falls"),
    BEDABIN_CAMP("Bedabin Camp"),
    BEEHIVES("Beehives"),
    BEWARE_OF_THE_MUSHROOMS("Beware of the mushrooms"),
    BEWARE_OF_THE_SCORPIONS("Beware of the scorpions"),
    BIRTHING_POOL("Birthing Pool"),
    BLACK_GUARD_HQ("Black Guard H.Q."),
    BLACK_KNIGHTS_BASE("Black Knights' Base"),
    BLACK_KNIGHTS_FORTRESS("Black Knights' Fortress"),
    BLACK_DEMONS("Black demons"),
    BLACK_DRAGONS("Black dragons"),
    BLAST_FURNACE("Blast Furnace"),
    BLIGHTED_CAVE("Blighted Cave"),
    BLOODVELDS("Bloodvelds"),
    BLOOMING_BURROW("Blooming Burrow"),
    BLUE_DRAGONS("Blue dragons"),
    BONE_COLLECTOR("Bone collector"),
    BONEYARD("Boneyard"),
    BONFIRE("Bonfire"),
    BOOT("Boot"),
    BOX_OF_HEALTH("Box of Health"),
    BREWERY("Brewery"),
    BRIMHAVEN("Brimhaven"),
    BRONZE_DRAGONS("Bronze dragons"),
    BRUTISH_DINOSAURS("Brutish dinosaurs"),
    BULBOUS_CRAWLERS("Bulbous crawlers"),
    BURGH_DE_ROTT("Burgh de Rott"),
    BURTHORPE("Burthorpe"),
    BURTHORPE_MINE("Burthorpe Mine"),
    BURTHORPE_SLAYER_CAVE("Burthorpe Slayer Cave"),
    BURTHORPE_TROLL_CAVE("Burthorpe Troll Cave"),
    CADARN("Cadarn"),
    CAIRN_ISLE("Cairn Isle"),
    CAMELOT_CASTLE("Camelot Castle"),
    CANIFIS("Canifis"),
    CAPTURED_TEMPLE("Captured Temple"),
    CASTLE_DRAKAN("Castle Drakan"),
    CASTLE_WARS("Castle Wars"),
    CATHEDRAL("Cathedral"),
    CATHERBY("Catherby"),
    CAVE("Cave"),
    CAVE_BUGS("Cave bugs"),
    CAVE_CRAWLERS("Cave crawlers"),
    CAVE_HORRORS_AND_ALBINO_BATS("Cave horrors & albino bats"),
    CHAMPIONS_CHALLENGE("Champions' Challenge"),
    CHAMPIONS_GUILD("Champions' Guild"),
    CHAOS_DRUIDS("Chaos druids"),
    CHAOS_DWARVES("Chaos dwarves"),
    CHAPEL("Chapel"),
    CHASM_OF_TEARS("Chasm of Tears"),
    CHINCHOMPA_PEN("Chinchompa Pen"),
    CHRISTMAS_VILLAGE("Christmas Village"),
    CHRONOZON("Chronozon"),
    CITHAREDE_ABBEY("Citharede Abbey"),
    CITY_OF_UM("City of Um"),
    CLAN_CAMP("Clan Camp"),
    CLAN_WARS("Clan Wars"),
    CLOCKTOWER("Clocktower"),
    COAL_TRUCKS("Coal Trucks"),
    COCKATRICE("Cockatrice"),
    COLOSSEUM("Colosseum"),
    COMBAT_TRAINING_CAMP("Combat Training Camp"),
    COMMANDER_AKHOMET("Commander Akhomet"),
    CONFUSION("Confusion"),
    COOKS_GUILD("Cooks' Guild"),
    COUNCIL_CHAMBER("Council chamber"),
    COURTHOUSE("Courthouse"),
    CRABS("Crabs"),
    CRADLE_OF_LIFE("Cradle of Life"),
    CRAFTING_GUILD("Crafting Guild"),
    CRANDOR("Crandor"),
    CRASH_ISLAND("Crash Island"),
    CROESUS_FRONT("Croesus Front"),
    CRUCIBLE("Crucible"),
    CRWYS("Crwys"),
    CRYPT_AND_SHADOW_SPIDERS("Crypt & shadow spiders"),
    CRYPT_OF_VARANUS("Crypt of Varanus"),
    CRYPT_RATS("Crypt rats"),
    CUSTOMS_OFFICE("Customs Office"),
    CYCLOSIS("Cyclosis"),
    DAEMONHEIM("Daemonheim"),
    DAGANNOTH("Dagannoth"),
    DAGANNOTH_KINGS("Dagannoth Kings"),
    DAGON_OVERLOOK("Dagon Overlook"),
    DAMAGED_WALL("Damaged wall"),
    DARK_BEASTS("Dark Beasts"),
    DARK_WARRIORS_FORTRESS("Dark Warriors' Fortress"),
    DARK_WIZARDS_TOWER("Dark Wizards' Tower"),
    DAVES_BASEMENT_OF_DOOM("Dave's Basement of Doom"),
    DAYGUARD_TOWER("Dayguard Tower"),
    DEAD_PEOPLE("Dead people"),
    DEATH_PLATEAU("Death Plateau"),
    DEEP_SEA_FISHING_HUB("Deep Sea Fishing Hub"),
    DEMONIC_RUINS("Demonic Ruins"),
    DESERT_MINING_CAMP("Desert Mining Camp"),
    DESERTED_KEEP("Deserted Keep"),
    DESERTED_MINE("Deserted Mine"),
    DEVILS_SNARES("Devil's snares"),
    DIANGOS_WORKSHOP("Diango's Workshop"),
    DISTILLERIES("Distilleries"),
    DISTILLERY("Distillery"),
    DOGS("Dogs"),
    DOMINION_GAMES_STADIUM("Dominion Games stadium"),
    DONDAKANS_ROCK("Dondakan's rock"),
    DRAGONS("Dragons"),
    DRAGONS_AND_FIRE_ELEMENTALS("Dragons & fire elementals"),
    DRAGONSTONE_DRAGONS("Dragonstone dragons"),
    DRAGONTOOTH_ISLAND("Dragontooth Island"),
    DRAMEN_TREE("Dramen Tree"),
    DRAYNOR_MANOR("Draynor Manor"),
    DRAYNOR_MANOR_BASEMENT("Draynor Manor basement"),
    DRAYNOR_SEWERS("Draynor Sewers"),
    DRAYNOR_VILLAGE("Draynor Village"),
    DUNGEON_OF_DISORDER("Dungeon of Disorder"),
    DUNGEON_RATS("Dungeon rats"),
    DUST_DEVILS("Dust devils"),
    DWARVEN_MINE("Dwarven Mine"),
    EAGLES_PEAK("Eagles' Peak"),
    EARTH_WARRIORS("Earth warriors"),
    EAST_ARDOUGNE("East Ardougne"),
    EAST_GRAVEYARD("East Graveyard"),
    EASTER_BUNNYS_HOUSE("Easter Bunny's house"),
    EASTFOLD_FARM("Eastfold Farm"),
    ECTOFUNTUS("Ectofuntus"),
    EDGEVILLE("Edgeville"),
    EDGEVILLE_MONASTERY("Edgeville Monastery"),
    EGG_PLANT("Egg Plant"),
    ELF_CAMP("Elf Camp"),
    ELVARG("Elvarg"),
    ENTRANA("Entrana"),
    ENTRANCE("Entrance"),
    ESSENCE_MINE("Essence Mine"),
    ETCETERIA("Etceteria"),
    EVERLIGHT_DIG_SITE("Everlight Dig Site"),
    EWEANS_GROVE("Ewean's Grove"),
    EXAM_CENTRE("Exam Centre"),
    EXILED_KALPHITE_HIVE("Exiled Kalphite Hive"),
    EXIT("Exit"),
    FALADOR("Falador"),
    FALCONER("Falconer"),
    FARM("Farm"),
    FEAR("Fear"),
    FELDIP_HILLS("Feldip Hills"),
    FENKENSTRAINS_CASTLE("Fenkenstrain's Castle"),
    FERAL_DINOSAURS("Feral dinosaurs"),
    FIGHT_ARENA("Fight Arena"),
    FIGHT_CAVE("Fight Cave"),
    FIGHT_PIT("Fight Pit"),
    FIRE_OBELISK("Fire Obelisk"),
    FIRE_GIANTS("Fire giants"),
    FISH_FARM("Fish Farm"),
    FISHING_FRENZY("Fishing Frenzy"),
    FISHING_GUILD("Fishing Guild"),
    FISHING_PLATFORM("Fishing Platform"),
    FIST_OF_GUTHIX("Fist of Guthix"),
    FLAX("Flax"),
    FORINTHRY_DUNGEON("Forinthry Dungeon"),
    FORT_FORINTHRY("Fort Forinthry"),
    FORT_FORINTHRY_PRISON("Fort Forinthry Prison"),
    FOUNTAIN_OF_HEROES("Fountain of Heroes"),
    FREMENNIK_ISLES("Fremennik Isles"),
    FREMENNIK_PROVINCE("Fremennik Province"),
    FROZEN_WASTE_PLATEAU("Frozen Waste Plateau"),
    GAMERS_GROTTO("Gamers' Grotto"),
    GARDEN_OF_KHARID("Garden of Kharid"),
    GARGOYLES("Gargoyles"),
    GIANT_ANTS("Giant ants"),
    GIANT_FROGS("Giant frogs"),
    GIANT_ROCK_CRABS("Giant rock crabs"),
    GIFT_OF_PEACE("Gift of Peace"),
    GLACOR_FRONT("Glacor Front"),
    GNOME_BALL_FIELD("Gnome Ball Field"),
    GOBLIN_CAMP("Goblin Camp"),
    GOBLIN_MAZE("Goblin Maze"),
    GOBLIN_MINE("Goblin Mine"),
    GOBLIN_VILLAGE("Goblin Village"),
    GOD_WARS_DUNGEON("God Wars Dungeon"),
    GOEBIE_CAMP("Goebie Camp"),
    GOLDEN_APPLE_TREE("Golden Apple Tree"),
    GOSHIMA("Goshima"),
    GOUTWEED_STORE("Goutweed store"),
    GRAIN_OF_PLENTY("Grain of Plenty"),
    GRAND_EXCHANGE("Grand Exchange"),
    GRAND_TREE("Grand Tree"),
    GRAND_VIZIER_EHSAN("Grand Vizier Ehsan"),
    GRAVEYARD("Graveyard"),
    GRAVEYARD_OF_SHADOWS("Graveyard of Shadows"),
    GREATER_DEMONS("Greater demons"),
    GREEN_DRAGONS("Green dragons"),
    GROTWORM_LAIR("Grotworm Lair"),
    GUTANOTH("Gu'Tanoth"),
    GUARDIANS("Guardians"),
    GUNNARSGRUNN("Gunnarsgrunn"),
    HAM_CULT("H.A.M. Cult"),
    HALL_OF_MEMORIES("Hall of Memories"),
    HAMMERSPIKES_HANGOUT("Hammerspike's hangout"),
    HARMONY("Harmony"),
    HARVEST_HOLLOW("Harvest Hollow"),
    HAUNTED_WOODS("Haunted Woods"),
    HAVENHYTHE("Havenhythe"),
    HEFIN("Hefin"),
    HELLHOUNDS("Hellhounds"),
    HEMENSTER("Hemenster"),
    HERBY_WERBY("Herby Werby"),
    HERE_BE_PENGUINS("Here Be Penguins"),
    HERE_BE_DEAD_STUFF("Here be dead stuff"),
    HERE_BE_GOBLINS("Here be goblins"),
    HEROES_GUILD("Heroes' Guild"),
    HEROES_GUILD_DUNGEON("Heroes' Guild Dungeon"),
    HETS_OASIS("Het's Oasis"),
    HIGHWEALD_FOREST("Highweald Forest"),
    HILL_GIANTS("Hill giants"),
    HOBGOBLINS("Hobgoblins"),
    HOLLOW_HILL("Hollow Hill"),
    HOPELESSNESS("Hopelessness"),
    HYDRA_PORTAL("Hydra portal"),
    HYDRIX_DRAGONS("Hydrix dragons"),
    ICE_MOUNTAIN("Ice Mountain"),
    ICE_PATH("Ice Path"),
    ICE_QUEENS_LAIR("Ice Queen's Lair"),
    ICE_GIANTS("Ice giants"),
    ICE_TROLLS("Ice trolls"),
    ICE_WARRIORS_AND_GIANTS("Ice warriors & giants"),
    ICEBERG("Iceberg"),
    IMPERIAL_DISTRICT("Imperial District"),
    INFERNAL_SOURCE_DIG_SITE("Infernal Source Dig Site"),
    INFERNAL_MAGI("Infernal magi"),
    INVENTION_GUILD("Invention Guild"),
    IORWERTH("Iorwerth"),
    IRON_AND_STEEL_DRAGONS("Iron & steel dragons"),
    IRON_ENCLAVE("Iron Enclave"),
    IRON_DRAGONS("Iron dragons"),
    ISAFDAR("Isafdar"),
    ITHELL("Ithell"),
    JADINKO_QUEEN("Jadinko Queen"),
    JAIL("Jail"),
    JALSAVRAH_PYRAMID("Jalsavrah Pyramid"),
    JATIZSO("Jatizso"),
    JELLIES("Jellies"),
    JELLYFISH("Jellyfish"),
    JIGGIG("Jiggig"),
    JOGRES("Jogres"),
    KALPHITE_HIVE("Kalphite Hive"),
    KALPHITE_NURSERY("Kalphite Nursery"),
    KALPHITE_GRAVEYARD("Kalphite graveyard"),
    KALPHITE_GUARDIANS("Kalphite guardians"),
    KALPHITE_SOLDIERS("Kalphite soldiers"),
    KANATAH("Kanatah"),
    KARAMJA("Karamja"),
    KEBBIT_PEN("Kebbit Pen"),
    KEEP_LE_FAYE("Keep Le Faye"),
    KELDAGRIM_ENTRANCE("Keldagrim Entrance"),
    KHARAZI_JUNGLE("Kharazi Jungle"),
    KHARID_ET_DIG_SITE("Kharid-et Dig Site"),
    KHARIDIAN_DESERT("Kharidian Desert"),
    KILN("Kiln"),
    KING_BLACK_DRAGON("King Black Dragon"),
    KINGS_CHAMBER("King's Chamber"),
    KINGS_ROAD("King's Road"),
    KINGDOM_OF_ASGARNIA("Kingdom of Asgarnia"),
    KINGDOM_OF_KANDARIN("Kingdom of Kandarin"),
    KINGDOM_OF_MISTHALIN("Kingdom of Misthalin"),
    KITCHEN("Kitchen"),
    KITCHENS("Kitchens"),
    KURASK("Kurask"),
    LABORATORY_PRIMUS("Laboratory Primus"),
    LABORATORY_QUARTUS("Laboratory Quartus"),
    LABORATORY_QUINTUS("Laboratory Quintus"),
    LABORATORY_SECUNDUS("Laboratory Secundus"),
    LABORATORY_SEXTUS("Laboratory Sextus"),
    LABORATORY_TERTIUS("Laboratory Tertius"),
    LAMPENFLORAS("Lampenfloras"),
    LAVA_MAZE("Lava Maze"),
    LEECHES("Leeches"),
    LEGENDS_GUILD("Legends' Guild"),
    LESSER_DEMONS("Lesser demons"),
    LIBRARY("Library"),
    LIGHTHOUSE("Lighthouse"),
    LIVERWORTS("Liverworts"),
    LIVING_ROCK_CAVERNS("Living rock caverns"),
    LIZARDS("Lizards"),
    LIZARDS_AND_ZAMORAK_FIGHTERS("Lizards & Zamorak fighters"),
    LLETYA("Lletya"),
    LUMBRIDGE("Lumbridge"),
    LUMBRIDGE_CASTLE_CELLAR("Lumbridge Castle cellar"),
    LUMBRIDGE_SWAMP("Lumbridge Swamp"),
    LUMINOUS_SNAGGLERS("Luminous snagglers"),
    LUNAR_ISLE("Lunar Isle"),
    MAGE_ARENA("Mage Arena"),
    MAGE_ARENA_BANK("Mage Arena bank"),
    MAGE_TRAINING_ARENA("Mage Training Arena"),
    MAIN_PLAZA("Main Plaza"),
    MAIZE_MAZE("Maize Maze"),
    MANOR_FARM("Manor Farm"),
    MARIGOLD_FARM("Marigold Farm"),
    MARIM("Marim"),
    MARKET("Market"),
    MASS_GRAVE("Mass grave"),
    MAUSOLEUM("Mausoleum"),
    MAZCAB("Mazcab"),
    MAZCAB_PORTAL("Mazcab Portal"),
    MCGRUBORS_WOOD("McGrubor's Wood"),
    MEILYR("Meilyr"),
    MEIYERDITCH("Meiyerditch"),
    MELZARS_MAZE("Melzar's Maze"),
    MEMORIAL_TO_GUTHIX_AND_HALL_OF_MEMORIES("Memorial to Guthix & Hall of Memories"),
    MENAPHOS("Menaphos"),
    MERCHANT_DISTRICT("Merchant District"),
    MINE("Mine"),
    MINECARTS("Minecarts"),
    MINES("Mines"),
    MINING_GUILD("Mining Guild"),
    MINNOW("Minnow"),
    MISCELLANIA("Miscellania"),
    MISCELLANIA_EXPANSION("Miscellania Expansion"),
    MITHRIL_DRAGONS("Mithril dragons"),
    MOKSHA_RITUAL_SITE("Moksha ritual site"),
    MONKS_OF_ZAMORAK("Monks of Zamorak"),
    MORT_MYRE_SWAMP("Mort Myre Swamp"),
    MORTTON("Mort'ton"),
    MORYTANIA("Morytania"),
    MOS_LEHARMLESS("Mos Le'Harmless"),
    MOSS_GIANTS("Moss giants"),
    MOSS_GOLEMS("Moss golems"),
    MOUNTAIN_CAMP("Mountain Camp"),
    MOUNTAIN_DWARVES("Mountain dwarves"),
    MUDSKIPPER_POINT("Mudskipper Point"),
    MUGGERS("Muggers"),
    MUMMIES("Mummies"),
    MUSA_POINT("Musa Point"),
    MUTATED_BLOODVELDS("Mutated bloodvelds"),
    MUTATED_JADINKO_BABIES("Mutated jadinko babies"),
    MUTATED_JADINKO_GUARDS("Mutated jadinko guards"),
    MUTATED_JADINKO_MALES("Mutated jadinko males"),
    NARDAH("Nardah"),
    NECHRYAEL("Nechryael"),
    NECROMANCER("Necromancer"),
    NEITIZNOT("Neitiznot"),
    NEMI_FOREST("Nemi Forest"),
    NIGHTGUARD_TOWER("Nightguard Tower"),
    NODON_FRONT("Nodon Front"),
    NORA_T_HAGGS_CELLAR("Nora T. Hagg's cellar"),
    NORTH_TUNNELS("North tunnels"),
    NOTHING_INTERESTING_HAPPENS_HERE("Nothing interesting happens here"),
    NURSERY("Nursery"),
    OBSERVATION_OUTPOST("Observation outpost"),
    OBSERVATORY("Observatory"),
    OBSTACLE_COURSE("Obstacle course"),
    OGRE_TOWER("Ogre Tower"),
    OGRES("Ogres"),
    OIKOI_HOUSEHOLDS("Oikoi (households)"),
    OLDAKS_TELEPORTATION_LABORATORY("Oldak's teleportation laboratory"),
    ONYX_DRAGONS("Onyx dragons"),
    OOGLOG("Oo'glog"),
    ORK_TOWER("Ork Tower"),
    ORTHEN_DIG_SITE("Orthen Dig Site"),
    OTHERWORLDLY_BEINGS("Otherworldly beings"),
    OTOT("Otot"),
    OTTOS_GROTTO("Otto's Grotto"),
    OUTPOST("Outpost"),
    PADDLINGTON("Paddlington"),
    PALACE("Palace"),
    PARK("Park"),
    PARTY_ROOM("Party Room"),
    PEST_CONTROL("Pest Control"),
    PICKAXE_FACTORY("Pickaxe factory"),
    PILLARS("Pillars"),
    PIRATES("Pirates"),
    PIRATES_COVE("Pirates' Cove"),
    PIRATES_HIDEOUT("Pirates' Hideout"),
    PISCATORIS_FISHING_COLONY("Piscatoris Fishing Colony"),
    PIT_OF_TRIALS("Pit of Trials"),
    PIT_SCORPIONS("Pit scorpions"),
    POISON_WASTE("Poison Waste"),
    POISON_SPIDERS("Poison spiders"),
    POISONOUS_SCORPIONS("Poisonous scorpions"),
    POLLNIVNEACH("Pollnivneach"),
    POLYPORE_DUNGEON("Polypore Dungeon"),
    PORT_DISTRICT("Port District"),
    PORT_KHAZARD("Port Khazard"),
    PORT_PHASMATYS("Port Phasmatys"),
    PORT_SARIM("Port Sarim"),
    PORT_TYRAS("Port Tyras"),
    PORTAL("Portal"),
    PRAETORIUM("Praetorium"),
    PRIFDDINAS("Prifddinas"),
    PRISON_BLOCK("Prison block"),
    PURO_PURO("Puro-puro"),
    PYRAMID("Pyramid"),
    PYREFIENDS("Pyrefiends"),
    QUARRY("Quarry"),
    QUEENS_CHAMBER("Queen's Chamber"),
    RANGING_GUILD("Ranging Guild"),
    RAT_PITS("Rat Pits"),
    RATS("Rats"),
    RECREATION("Recreation"),
    RED_DRAGON_ISLE("Red Dragon Isle"),
    RED_DRAGONS("Red dragons"),
    RED_SPIDERS("Red spiders"),
    RELLEKKA("Rellekka"),
    RESEARCH_AND_DEVELOPMENT("Research and Development"),
    REVENANTS("Revenants"),
    RIMMINGTON("Rimmington"),
    RIPPER_DEMONS("Ripper demons"),
    RIPPER_DINOSAURS("Ripper dinosaurs"),
    RIVER_ELID("River Elid"),
    RIVER_KELDA("River Kelda"),
    RIVER_LUM("River Lum"),
    RIVER_SALVE("River Salve"),
    ROCK_CRABS("Rock crabs"),
    ROCK_LOBSTERS("Rock lobsters"),
    ROCK_SLUGS("Rock slugs"),
    ROCKS("Rocks"),
    RODDECKS_HIDEOUT("Roddeck's hideout"),
    ROGUES_CASTLE("Rogues' Castle"),
    ROGUES_DEN("Rogues' Den"),
    ROOTS("Roots"),
    RUINS("Ruins"),
    RUINS_OF_UZER("Ruins of Uzer"),
    RUNEFEST_TREASURE_ISLAND("RuneFest Treasure Island"),
    SAILFISH("Sailfish"),
    SALARIN_THE_TWISTED("Salarin the Twisted"),
    SANGUINESTI_REGION("Sanguinesti Region"),
    SANTAS_LODGE("Santa's Lodge"),
    SARADOMINS_ENCAMPMENT("Saradomin's Encampment"),
    SCORPION_PIT("Scorpion Pit"),
    SEA_SNAKES("Sea snakes"),
    SEERS_VILLAGE("Seers' Village"),
    SENNTISTEN("Senntisten"),
    SERENS_ENCAMPMENT("Seren's Encampment"),
    SHADES("Shades"),
    SHADOW_HOUNDS_AND_WOLVES("Shadow hounds & wolves"),
    SHADOW_SPIDERS("Shadow spiders"),
    SHADOW_WARRIORS("Shadow warriors"),
    SHANTAY_PASS("Shantay Pass"),
    SHATTERED_WORLDS("Shattered Worlds"),
    SHIFTING_TOMBS("Shifting Tombs"),
    SHILO_VILLAGE("Shilo Village"),
    SHIPYARD("Shipyard"),
    SHRINE("Shrine"),
    SHRINE_OF_INANNA("Shrine of Inanna"),
    SILVAREA("Silvarea"),
    SINCLAIR_MANSION("Sinclair Mansion"),
    SKELETAL_AND_ZOMBIE_HANDS("Skeletal and zombie hands"),
    SKELETAL_WYVERNS("Skeletal wyverns"),
    SKELETONS("Skeletons"),
    SKELETONS_AND_ZOMBIES("Skeletons & zombies"),
    SKINWEAVER("Skinweaver"),
    SKULLBALL("Skullball"),
    SLAYER_TOWER("Slayer Tower"),
    SLEEPING_DRAGON("Sleeping dragon"),
    SLISKES_NECROPOLIS("Sliske's Necropolis"),
    SNOWBALL_ARENA("Snowball Arena"),
    SOLDIERS("Soldiers"),
    SOPHANEM("Sophanem"),
    SOPHANEM_DUNGEON("Sophanem Dungeon"),
    SOPHANEM_SLAYER_DUNGEON("Sophanem Slayer Dungeon"),
    SORCERERS_TOWER("Sorcerer's Tower"),
    SOUL_OBELISK("Soul Obelisk"),
    SOUL_WARS("Soul Wars"),
    SOUTH_FELDIP_HILLS("South Feldip Hills"),
    SOUTH_TUNNELS("South tunnels"),
    SPIDERS("Spiders"),
    SPIRIT_GROVE_REX_MATRIARCHS("Spirit grove (Rex Matriarchs)"),
    STAGE("Stage"),
    STAR_LODGE_CELLAR("Star Lodge cellar"),
    START_OF_CARNILLEAN_RISING("Start of Carnillean Rising"),
    STATION("Station"),
    STEALING_CREATION("Stealing Creation"),
    STEEL_DRAGONS("Steel dragons"),
    STORMGUARD_CITADEL_DIG_SITE("Stormguard Citadel Dig Site"),
    SUNKEN_PYRAMID("Sunken Pyramid"),
    SWAMP("Swamp"),
    SWAMP_CAVE("Swamp Cave"),
    SWARM("Swarm"),
    TAI_BWO_WANNAI("Tai Bwo Wannai"),
    TANGLEFEET("Tanglefeet"),
    TAVERLEY("Taverley"),
    TEARS_OF_GUTHIX("Tears of Guthix"),
    TEGDAK("Tegdak"),
    TEMPLE("Temple"),
    TERROR_DOGS("Terror dogs"),
    THALMUNDS_FORGE("Thalmund's forge"),
    THE_ARC("The Arc"),
    THE_FORGOTTEN_CEMETERY("The Forgotten Cemetery"),
    THE_HARROWING("The Harrowing"),
    THE_HEART("The Heart"),
    THE_HOLLOWS("The Hollows"),
    THE_ISLANDS_THAT_ONCE_WERE_TURTLES("The Islands That Once Were Turtles"),
    THE_LOST_GROVE("The Lost Grove"),
    THRONE_ROOM("Throne room"),
    THUGS("Thugs"),
    TIRANNWN("Tirannwn"),
    TOWER_OF_LIFE("Tower of Life"),
    TRAHAEARN("Trahaearn"),
    TRAWLER("Trawler"),
    TREE_GNOME_STRONGHOLD("Tree Gnome Stronghold"),
    TREE_GNOME_VILLAGE("Tree Gnome Village"),
    TROLL_STRONGHOLD("Troll Stronghold"),
    TROLL_TOWER("Troll Tower"),
    TROLL_GENERALS("Troll generals"),
    TROLLHEIM("Trollheim"),
    TROLLS("Trolls"),
    TROLLWEISS_MOUNTAIN("Trollweiss Mountain"),
    TUAI_LEIT("Tuai Leit"),
    TUROTH("Turoth"),
    TYRAS_CAMP("Tyras Camp"),
    TZEKHAAR_FRONT("TzekHaar Front"),
    UNDERGROUND_PASS("Underground Pass"),
    UNDERGROUND_PIG_PEN("Underground pig pen"),
    UNDERWATER_CAVE("Underwater cave"),
    UNGAEL("Ungael"),
    UR_MEG("Ur-meg"),
    UR_TAG("Ur-tag"),
    UR_VASS("Ur-vass"),
    UR_ZEK_AND_UR_TAAL("Ur-zek & Ur-taal"),
    VTAM_CORPORATION("VTAM Corporation"),
    VARROCK("Varrock"),
    VARROCK_DIG_SITE("Varrock Dig Site"),
    VAULT("Vault"),
    VENOMOUS_DINOSAURS("Venomous dinosaurs"),
    VESTIBULE_OF_FUTILITY("Vestibule of Futility"),
    VINECRAWLERS("Vinecrawlers"),
    VOID_KNIGHTS_OUTPOST("Void Knights' Outpost"),
    VOLCANO("Volcano"),
    VULTURES("Vultures"),
    WAIKO("Waiko"),
    WALLASALKI("Wallasalki"),
    WARFORGE_DIG_SITE("Warforge Dig Site"),
    WARRIORS_GUILD("Warriors' Guild"),
    WATERBIRTH_ISLAND("Waterbirth Island"),
    WATERFIENDS("Waterfiends"),
    WATERMILL_CELLAR("Watermill cellar"),
    WENDLEWICK("Wendlewick"),
    WEST_ARDOUGNE("West Ardougne"),
    WEST_GRAVEYARD("West Graveyard"),
    WHALES_MAW("Whale's Maw"),
    WHITE_KNIGHT_CAMP("White Knight Camp"),
    WHITE_KNIGHTS_CASTLE("White Knights' Castle"),
    WHITE_WOLF_MOUNTAIN("White Wolf Mountain"),
    WILDERNESS("Wilderness"),
    WILDERNESS_CRATER("Wilderness Crater"),
    WIRE_MACHINE("Wire machine"),
    WISPS_OF_THE_GROVE("Wisps of the grove"),
    WITCHAVEN("Witchaven"),
    WIZARDS_GUILD("Wizards' Guild"),
    WIZARDS_TOWER("Wizards' Tower"),
    WORKERS_DISTRICT("Workers District"),
    WORKSHOP("Workshop"),
    XOLO_CITY("Xolo city"),
    YANILLE("Yanille"),
    YOUR_CAMP("Your Camp"),
    ZAMORAK_FIGHTERS("Zamorak fighters"),
    ZAMORAKS_FORTRESS("Zamorak's Fortress"),
    ZAMORAKS_RAMPART("Zamorak's Rampart"),
    ZANIKS_BEDROOM("Zanik's bedroom"),
    ZARADOR("Zarador"),
    ZAROSS_BASTION("Zaros's Bastion"),
    ZOLAREA("Zolarea"),
    ZOLAREA_CORE("Zolarea Core"),
    ZOMBIES("Zombies"),
    ZOMBIES_SKELETONS_AND_ANIMATED_ITEMS("Zombies, skeletons & animated items");

    private static final Map<String, WorldMapIcon> BY_NAME = new HashMap<>();

    static {
        for (WorldMapIcon icon : values()) {
            BY_NAME.put(icon.displayName.toLowerCase(), icon);
        }
    }

    private final String displayName;

    WorldMapIcon(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Returns the exact display name as it appears on the world map.
     *
     * @return the display name
     */
    public String displayName() {
        return displayName;
    }

    /**
     * Looks up an icon by its display name (case-insensitive).
     *
     * @return the matching icon, or {@code null} if not found
     */
    public static WorldMapIcon fromName(String name) {
        return name == null ? null : BY_NAME.get(name.toLowerCase());
    }
}
